### PR TITLE
[mhwdcfg] replace hardwarecfg

### PR DESCRIPTION
**Pull request by hphilm**
Marcus ported **mhwd.sh** to python3 within **mhwdcfg** module. This module is already tested with several **calamares-dev** packages and **dev-builds**. Please review the module and comment if still some is open or creates issues with it.

### CODE REVIEW

**Comment by udeved** [comment]
If the local setting is false, mhwd will use online repo.
Just note to myself, to add dropping repo on iso if false in buildiso.

**Comment by hphilm** [comment]
Ok, however this is more about the module **mhwdcfg** as is and if it is designed final and tested. On my end it works fine.

**Comment by udeved** [comment]
Worked fine for me in the two cases in multiple test installs.

**Comment by hphilm** [comment]
Excellent. @ste74, @oberon2007, any doubts with this new module?

**Comment by udeved** [comment]
But also here, if local is false the mirror ranking is crucial point.

https://github.com/manjaro/calamares/commit/6927ca643961a9f83963a23d7795ccd24044d248

**Comment by hphilm** [comment]
**mwhd** doesn't need mirror ranking with local repository. For online repositories it might be useful. However the mirrorlist is never broken, might only be configured for a slower mirror.

**Comment by udeved** [comment]
Yet, but I encountered slow mirror and mhwd failed when mirror timed out.

**Comment by hphilm** [comment]
Makes sense. We might create a **rankmirrors** module for that ...

**Comment by udeved** [comment]
Could be my evening fun, I have some time tonight.
Perhaps support arch linux with that module too.

**Comment by hphilm** [comment]
Be creative and keep upstream in mind. Lets see if Teo will merge our final PR for **plymouthcfg**.

**Comment by Ste74** [comment]
> If the local setting is false, mhwd will use online repo.
> Just note to myself, to add dropping repo on iso if false in buildiso.

Exactly what is this module? how works ? Only for my understanding :smile_cat: . I have just now switched on 0.13.x series and into master on github to build an iso of budgie in unstable

**Comment by hphilm** [comment]
This module replaces the old **hardwarecfg** module we used from the beginning. It is a total rewrite in **python**. If you have built an ISO with **calamares-dev** and used **mt-0.13.x** it is used by default. So far I don't see any issue with it. Well, some user [posted some](https://forum.manjaro.org/t/manjaro-xfce-minimal-16-10-dev-unstable-x86-64-install-problem/9065/1) in our forum, but might be something else ...

**Comment by udeved** [comment]
I'll push a slight optimizing of iteration, it will just change iteration through bus first, and ids second.

**Comment by hphilm** [comment]
Ok, If so, please also update **calamares-dev** and this **PR** so we can test it. Thx.

**Comment by udeved** [comment]
Btw, do we have any gfx cards on usb bus to check?
It currently does.

**Comment by hphilm** [comment]
In a later state we had USB support also in mind. Currently we have only pci profiles. However it is coded like this and needed to pass the switch ...

**Comment by hphilm** [comment]
Btw, for **video** we support also the IDs **0302** and **0380**.

**Comment by udeved** [comment]
Ok, I'll update the conf with the ids

**Comment by udeved** [comment]
Did I understand right. and usb is unused on video, or also unused on net ids?
I guess net usb is implemented?

**Comment by hphilm** [comment]
For now **usb** is not yet used at all. We have [no configs](https://github.com/manjaro/mhwd-db) written for it ...

**Comment by udeved** [comment]
Should I deactivate usb check until implemented?

**Comment by hphilm** [comment]
What happens if it is activated? Maybe add a TODO so we remember it ...

**Comment by udeved** [comment]
```
bus:
    - pci

identifier:
    net:
      - 200
      - 280
    video:
      - 300
      - 302
      - 380
```

I'd push this, we just have to add usb once implemented, no code changes

**Comment by Ste74** [comment]
`==> Prepare [manjaro/iso/EFI]
mkfs.fat 4.0 (2016-05-06)
  -> Copying boot images ...
  -> Using intel_ucode.img ...
  -> Copying efi loaders ...
  -> Writing loader.conf ...
  -> Writing uefi-shell-v1-x86_64.conf ...
  -> Writing uefi-shell-v2-x86_64.conf ...
  -> Writing manjaro-x86_64.conf ...
  -> Using intel_ucode.img ...
  -> Writing manjaro-x86_64-nonfree.conf ...
  -> Using intel_ucode.img ...
  -> Copying shellx64_v1.efi ...
  -> Copying shellx64_v2.efi ...
cp: error writing '/build/manjaro-tools/buildiso/budgie/x86_64/efiboot/EFI/shellx64_v2.efi': No space left on device
==> ERROR: A failure occurred in make_efiboot().
    Aborting...
[stefano@ste74 ~]$ 

Maybe i have forgotten something ? ( check the /build partition but no full ( 65 Gb free ))

**Comment by udeved** [comment]
Ste, please don't post on calamares buildiso issue.

**Comment by Ste74** [comment]
:+1: ok open on bugtrucker

**Comment by hphilm** [comment]
The latest code of this can be found in **calamares-dev 2.4.1.r2455.c70e91f-1**. Please test and give feedback. @oberon2007, @Ste74.

**Pull request merged**
